### ISSUE TITLE
Information mismatch on competition website and github

### ISSUE THREAD

**Issue by prabhant** [cxxz/automl_decathlon_starter_kit#1]
Hi on the competition website it's written to "Run python download_public_datasets.py in the starter kit (available on [GitHub](https://github.com/cxxz/automl_decathlon_starter_kit)) to download the 10 public development datasets and corresponding metadata."

and this repository has no file like that, can you please correct it to avoid confusion

**Comment by nick11roberts** [comment]
Codalab been updated -- thanks for noticing this!
